// Code generated by mockery. DO NOT EDIT.

package mockconfig

import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *Storage) Get(key string) (string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Storage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *Storage_Expecter) Get(key interface{}) *Storage_Get_Call {
	return &Storage_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *Storage_Get_Call) Run(run func(key string)) *Storage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Storage_Get_Call) Return(url string, err error) *Storage_Get_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *Storage_Get_Call) RunAndReturn(run func(string) (string, error)) *Storage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: key, url, overwrite
func (_m *Storage) Store(key string, url string, overwrite bool) error {
	ret := _m.Called(key, url, overwrite)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = rf(key, url, overwrite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type Storage_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - key string
//   - url string
//   - overwrite bool
func (_e *Storage_Expecter) Store(key interface{}, url interface{}, overwrite interface{}) *Storage_Store_Call {
	return &Storage_Store_Call{Call: _e.mock.On("Store", key, url, overwrite)}
}

func (_c *Storage_Store_Call) Run(run func(key string, url string, overwrite bool)) *Storage_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *Storage_Store_Call) Return(_a0 error) *Storage_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Store_Call) RunAndReturn(run func(string, string, bool) error) *Storage_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
