// Package nolint provides code analyzer wrapper that checks for existing
// "//lint:file-ignore ..." comment inside first comment group and skips entire file
// in case such comment exists.
//
// Approach is inspired by https://github.com/kyoh86/nolint but here it's much more simple.
package nolint

import (
	"go/ast"
	"reflect"
	"strings"

	"golang.org/x/tools/go/analysis"
)

const (
	noLintPrefix          = "//lint:file-ignore "
	codeGeneratedByPrefix = "// Code generated by "
)

// WrapSlice wraps slice of analyzers.
func WrapSlice(as []*analysis.Analyzer) {
	for _, a := range as {
		Wrap(a)
	}
}

// Wrap overwrites analyzer's run function adding check for "//lint:file-ignore "
// and "// Code generated by " in comments.
//
// If one of such lines exists in first comment group, it removes file from analysis.Pass.
// After comment check, usual run() logic is called if some (or all) files still remain.
func Wrap(a *analysis.Analyzer) {
	realRun := a.Run
	a.Run = func(pass *analysis.Pass) (any, error) {
		var newFiles []*ast.File
	Loop:
		for _, file := range pass.Files {
			if len(file.Comments) > 0 {
				for _, comment := range file.Comments[0].List {
					for _, prefix := range []string{noLintPrefix, codeGeneratedByPrefix} {
						if strings.HasPrefix(comment.Text, prefix) && len(comment.Text) > len(prefix) {
							continue Loop
						}
					}
				}
			}
			newFiles = append(newFiles, file)
		}
		if len(newFiles) == 0 {
			return reflect.TypeOf(a.ResultType), nil
		}
		pass.Files = newFiles
		return realRun(pass)
	}
}
